### ISSUE TITLE
Attempt to update event data and time

### ISSUE THREAD

**Issue by slangnas** [cis498-g4/GuestBook#40]
Attempt to update time of event. The date and time options did not pop up, entered random text and attempted to update
<img width="1257" alt="screen shot 2017-05-08 at 8 19 54 pm" src="https://cloud.githubusercontent.com/assets/17203816/25831743/c0a9887e-342b-11e7-97de-11892193fb8d.png">
. 
<img width="676" alt="screen shot 2017-05-08 at 8 01 36 pm" src="https://cloud.githubusercontent.com/assets/17203816/25831459/e3eab5e4-3429-11e7-9ce9-aa2c878fc9b0.png">

**Comment by mikemolenda** [comment]
Fix by adding data formatting validation for AddEvent

**Comment by mikemolenda** [comment]
Addressed 5/10/17
